<a href="https://colab.research.google.com/github/dangdang2222/NLP_basic/blob/main/pytorch_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###nn.Embedding()

단어 -> 정수 인덱스 -> 임베딩 층 -> 임베딩 벡터(밀집 벡터)

In [1]:
train_data = 'you need to know how to code'

word_set = set(train_data.split())
word_set

{'code', 'how', 'know', 'need', 'to', 'you'}

In [2]:
vocab = {token: i+2 for i, token in enumerate(word_set)}
vocab['<unk>']=0
vocab['<pad>']=1

num_embeddings : 임베딩 할 단어 개수 = 단어 집합 크기

embedding_dim : 임베딩 벡터 차원

padding_idx : 패딩을 위한 토큰 인덱스

In [3]:
import torch.nn as nn
embedding_layer = nn.Embedding(num_embeddings=len(vocab), embedding_dim=3, padding_idx=1)

In [4]:
print(embedding_layer.weight)

Parameter containing:
tensor([[-0.9412, -0.4930, -0.0993],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.5008,  1.3809, -1.5302],
        [ 2.3237, -0.8300, -1.5274],
        [-0.3354,  0.8400,  0.8535],
        [-0.9597,  0.6872,  1.0241],
        [ 1.6532, -0.1332,  0.5569],
        [-0.9533, -0.7693,  0.2373]], requires_grad=True)


---
## Pretrained Word Embedding

미 훈련되어져 있는 워드 임베딩을 불러서 이를 임베딩 벡터로 사용 => 훈련 데이터가 부족한 상황에서 사용

In [13]:
!python -c 'from torch.utils.collect_env import main; main()'

PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.26

Python version: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.

In [14]:
!pip install torchtext==0.9.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 7.1 MB 5.1 MB/s 
     |████████████████████████████████| 735.5 MB 14 kB/s 
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1+cu113
    Uninstalling torch-1.12.1+cu113:
      Successfully uninstalled torch-1.12.1+cu113
  Attempting uninstall: torchtext
    Found existing installation: torchtext 0.13.1
    Uninstalling torchtext-0.13.1:
      Successfully uninstalled torchtext-0.13.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.13.1+cu113 requires torch==1.12.1, but you have torch 1.8.0 which is incompatible.
torchaudio 0.12.1+cu113 requires torch==1.12.1, but you have torch 1.8.0 which is incompatible.


In [1]:
from torchtext.legacy import data

In [2]:
from torchtext.legacy import datasets

In [3]:
TEXT = data.Field(sequential=True, batch_first=True, lower=True)
LABEL = data.Field(sequential=False, batch_first=True)

In [4]:
trainset, testset = datasets.IMDB.splits(TEXT,LABEL)

downloading aclImdb_v1.tar.gz


aclImdb_v1.tar.gz: 100%|██████████| 84.1M/84.1M [00:05<00:00, 14.7MB/s]


In [5]:
print(len(trainset),len(testset))

25000 25000


In [6]:
vars(trainset[0])

{'text': ['i',
  'watched',
  'this',
  'movie',
  'once',
  'and',
  'might',
  'watch',
  'it',
  'again,',
  'but',
  'although',
  'jamie',
  'foxx',
  'is',
  'good',
  'in',
  'the',
  'movie,',
  'i',
  'feel',
  'they',
  'could',
  'have',
  'used',
  'a',
  "'less",
  "funny'",
  'character',
  'as',
  'alvin',
  'sanders.',
  "foxx's",
  'scenes',
  'for',
  'instance',
  'in',
  'the',
  'jail',
  'when',
  'he',
  'is',
  'confronted',
  'by',
  'edgar',
  'clenteen',
  '(david',
  'morse)',
  'are',
  'too',
  'funny.',
  'david',
  'morse',
  'again',
  'is',
  'a',
  'wonderful',
  'portrayer',
  'of',
  'a',
  'cop.',
  'his',
  'tough',
  'yet',
  'mostly',
  'quiet',
  'features',
  'are',
  'perfect',
  'for',
  'his',
  'role.',
  'once',
  'again',
  'morse',
  'meets',
  'doug',
  'hutchinson',
  '(bristol)',
  'in',
  'the',
  'theater.',
  'morse',
  'ends',
  'up',
  'coming',
  'down',
  'hard',
  'on',
  'hutchinson.',
  'they',
  'are',
  'both',
  'perfect

torchtext에서 제공하는 pretrained된 워드 임베딩

glove.6B.300d를 사용하자

In [8]:
from torchtext.vocab import GloVe

In [9]:
TEXT.build_vocab(trainset, vectors=GloVe(name='6B',dim=300),max_size=10000,min_freq=10)
LABEL.build_vocab(testset)

.vector_cache/glove.6B.zip: 862MB [02:39, 5.40MB/s]                           
100%|█████████▉| 399999/400000 [00:42<00:00, 9473.81it/s]


In [10]:
TEXT.vocab.stoi

defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x7f4d3943bb90>>,
            {'<unk>': 0,
             '<pad>': 1,
             'the': 2,
             'a': 3,
             'and': 4,
             'of': 5,
             'to': 6,
             'is': 7,
             'in': 8,
             'i': 9,
             'this': 10,
             'that': 11,
             'it': 12,
             '/><br': 13,
             'was': 14,
             'as': 15,
             'for': 16,
             'with': 17,
             'but': 18,
             'on': 19,
             'movie': 20,
             'his': 21,
             'are': 22,
             'not': 23,
             'film': 24,
             'you': 25,
             'have': 26,
             'he': 27,
             'be': 28,
             'at': 29,
             'one': 30,
             'by': 31,
             'an': 32,
             'they': 33,
             'from': 34,
             'all': 35,
             'who': 36,
             'like

In [11]:
print(TEXT.vocab.vectors.shape)

torch.Size([10002, 300])


임베딩 벡터는 총 10,002개가 존재하며 각 단어는 300차원


In [12]:
print(TEXT.vocab.vectors[0])
print(TEXT.vocab.vectors[1])
print(TEXT.vocab.vectors[10])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [16]:
import torch.nn as nn
import torch
embedding_layer = nn.Embedding.from_pretrained(TEXT.vocab.vectors, freeze=False)

In [17]:
embedding_layer(torch.LongTensor([10]))

tensor([[-2.0437e-01,  1.6431e-01,  4.1794e-02, -1.3708e-01, -2.9779e-01,
          3.3440e-01, -6.9955e-02, -6.8036e-02,  1.0604e-01, -2.0337e+00,
          1.7977e-01, -7.7403e-02, -1.9518e-01,  1.8324e-01,  3.0017e-02,
         -5.4762e-02, -4.5725e-01, -2.4509e-02,  5.7387e-02, -3.4878e-01,
          3.9696e-02,  4.4826e-01, -5.8462e-02,  4.1181e-01, -3.5411e-02,
         -1.4722e-01,  1.0740e-01, -2.5896e-01, -1.1658e-01,  1.9822e-01,
          3.2850e-01,  2.4177e-01, -5.7177e-01, -5.6442e-02, -9.6437e-01,
          3.4482e-01,  5.4639e-02,  2.3828e-01, -1.9139e-01,  3.0899e-01,
          2.8044e-01, -3.3814e-02, -2.5436e-01,  1.5373e-02,  1.6341e-01,
          2.6352e-01,  1.5812e-01,  3.2044e-01, -2.3082e-01,  2.6050e-01,
          2.0606e-01, -8.9769e-02, -1.0055e-01,  7.0378e-02, -2.7452e-02,
          2.7959e-01, -9.5862e-02,  2.0574e-01,  2.9522e-01, -1.2285e-02,
          1.1164e-01, -5.1373e-02,  4.6106e-01,  2.3014e-02, -3.7141e-01,
         -2.4166e-01,  3.3773e-02,  3.